export default function Legal() {
  return (
    <div className="pt-24 pb-24 px-6">
      <div className="max-w-3xl mx-auto prose prose-invert prose-sm">
        <h1 className="text-4xl font-bold text-white mb-8">Legal & Disclaimer</h1>

        <h2 className="text-xl font-semibold text-white mt-8 mb-3">Disclaimer</h2>
        <p className="text-gray-400">
          Singularity Engine is provided as-is, without warranty of any kind. AI-generated applications
          may contain bugs, security issues, or unexpected behavior. Use at your own risk.
        </p>

        <h2 className="text-xl font-semibold text-white mt-8 mb-3">Acceptable Use</h2>
        <ul className="text-gray-400 space-y-1 list-disc pl-5">
          <li>No illegal or harmful content</li>
          <li>No prompt injection or attempts to exploit the system</li>
          <li>No data collection through generated apps</li>
          <li>No impersonation of individuals or organizations</li>
        </ul>

        <h2 className="text-xl font-semibold text-white mt-8 mb-3">Generated Content</h2>
        <p className="text-gray-400">
          Applications generated by Singularity Engine are created autonomously by AI. The maintainers
          of Singularity Engine do not review, endorse, or take responsibility for the content,
          functionality, or safety of generated applications.
        </p>

        <h2 className="text-xl font-semibold text-white mt-8 mb-3">Third-Party Services</h2>
        <p className="text-gray-400">
          Singularity Engine uses third-party services including Amazon Web Services (AWS), GitHub,
          X (Twitter), and Anthropic (Claude). Your use of Singularity Engine is also subject to the
          terms of service of these providers.
        </p>

        <h2 className="text-xl font-semibold text-white mt-8 mb-3">License</h2>
        <p className="text-gray-400">
          Singularity Engine is open source under the{" "}
          <a href="https://opensource.org/licenses/MIT" className="text-[#00d4ff] hover:underline">MIT License</a>.
        </p>
      </div>
    </div>
  );
}
